# Diese Workflow-Datei automatisiert den Build und Deploy-Prozess für GitHub Pages
# Sie wird automatisch ausgeführt, wenn Sie Änderungen zum main Branch pushen

name: Build and Deploy Jekyll Site

# Definiert, wann dieser Workflow ausgeführt wird
on:
  # Wird ausgeführt bei Push zum main Branch
  push:
    branches: [ main ]
  # Wird ausgeführt bei Pull Requests zum main Branch
  pull_request:
    branches: [ main ]
  # Ermöglicht manuellen Start des Workflows
  workflow_dispatch:

# Setzt Berechtigungen für GitHub Token
permissions:
  contents: read
  pages: write
  id-token: write

# Verhindert gleichzeitige Deployments
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build-Job: Erstellt die Jekyll-Site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
        
      - name: Build Jekyll Site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
          
      - name: Upload Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site/

  # Deploy-Job: Veröffentlicht die gebaute Site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # Führt Deploy nur bei Push zum main Branch aus (nicht bei PRs)
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
